### ISSUE TITLE
Hey balibalo, could you explain what is this?

### ISSUE THREAD

**Issue by nxvvvv** [BaliBalo/DiscordTV#8]

**Comment by BaliBalo** [comment]
Hey !
This is to display a little moveable widget inside the discord window that can be used to play youtube videos. If multiple users have it installed, the playback is synchronized between them (starting a video, pausing, jumping to a different time, etc. will be simultaneous for all users), so that can be used to react to youtube videos together for example.

Currently there might be a few things a bit specific to the server I made it for, but most of it is quite generic

**Comment by nxvvvv** [comment]
Cool, so this is a discord based watchparty thingy?

**Comment by BaliBalo** [comment]
Yeah pretty much! For youtube only, currently.
There are also a few things that I wanted to improve (for example the thing is removed and needs to be reinstalled after each discord update), but it does the job

**Comment by nxvvvv** [comment]
Cool dude. I'll surely check it out. :)
